name: Publish Docker Hub
on:
  release:
    types: [edited,created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: loop3d/loopstructural
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: Dockerfile
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
