name: Build documentation and deploy

on:
  push:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-activate-base: true
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.10.1-0/Miniforge-pypy3-4.10.1-0-Linux-x86_64.sh
          channels: anaconda,conda-forge,loop3d,conda-forge/label/cf202003
          python-version: 3.9
      - name: Build documentation 
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
            conda install -c conda-forge theano cython numpy pandas imageio scipy matplotlib  sphinx sphinx-gallery sphinxcontrib-bibtex pydata-sphinx-theme myst-parser scikit-learn scikit-image pyamg flake8 pytest networkx python=3.9   -y
            pip install lavavu-osmesa 
            python setup.py install build_ext --inplace
            cd docs
            make html