name: Python package build and publish

on:
  release:
    types: [edited, created]

jobs:
  build_wheels_macos:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-*"
          CIBW_BEFORE_BUILD: "pip install numpy==1.18 cython" #make sure numpy is the same version as required by LS

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run : |
          pip install twine
          python -m twine upload ./wheelhouse/*.whl       
